### PR TITLE
Minor fixes/tweaks to conform to latest Swift version

### PR DESCRIPTION
**Pull request by codymoorhouse**
- 'C' style loops will soon be deprecated, [click here](http://bjmiller.me/post/137624096422/on-c-style-for-loops-removed-from-swift-3)
- The '--' and '++' operators are already deprecated
- Fixed some minor syntax issues throughout
- Clarified grammar regarding portrait view checkbox

### CODE REVIEW

**Comment by stanidesis** [comment]
@codymoorhouse thanks for the PR! Did you test all of these in-game?

**Comment by codymoorhouse** [comment]
Yup I tested them as I followed the tutorial, was a great tutorial by the way, so thanks very much :+1:

**Comment by stanidesis** [comment]
Thanks @codymoorhouse and you're welcome!

**Comment by stanidesis** [comment]
@codymoorhouse the fixes are live 👍

**Comment by codymoorhouse** [comment]
Awesome, glad I could help out!

Cody Moorhouse
cody.moorhouse@icloud.com
(780)938-3008

**Pull request merged**
